### PR TITLE
Tagline Changed by Yazdan

### PR DESCRIPTION
**Pull request by YazdanRizwan**
One issue of changing tagline is resolved

### CODE REVIEW

**Comment by Manvityagi** [comment]
On my phone screen, tagline is still the unchanged one.

**Comment by YazdanRizwan** [comment]
I think they haven't merged my pull request don't know why!!

**Comment by YazdanRizwan** [comment]
Sorry, but I am new on Github. Without merging u can see the changes??

**Comment by Manvityagi** [comment]
> Sorry, but I am new on Github. Without merging u can see the changes??

Hey @YazdanRizwan, Yes, the repo. has CI/CD integration with netlfiy. Anyone can see the deploy preview of any PR.
Here it is - https://deploy-preview-190--girlcodeit.netlify.app/
You can find this in Successful Checks under your PR.

**Pull request closed without merging**
