### PR TITLE
Navbar issue fixed

### PR DESCRIPTION
**Pull request by ArunTeltia**
# Description
Fixing #184 
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
This PR redirect the user when he/she clicked on navbar links and redirect to home page of the specific section

Please check options that are relevant to your PR.

 Bug fixed (non-breaking change which fixes an issue)
 This change does not requires a documentation update

# Checklist:

- [ x ] I have squashed my commits
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings

### CODE REVIEW

**Comment by ArunTeltia** [comment]
@abdus please review

**Comment by ArunTeltia** [comment]
@abdus please review

**Comment by Manvityagi** [comment]
Same Problem @abdus, On navigating Titles of the sections are hidden :/

CC: @ArunTeltia

**Comment by ArunTeltia** [comment]
Can you tell me on which browser you checked this @Manvityagi di

**Comment by Manvityagi** [comment]
> Can you tell me on which browser you checked this @Manvityagi di

Chrome

**Comment by abdus** [comment]
> @abdus please review

sorry, bro. I didn't check this thread earlier.

> Same Problem @abdus, On navigating Titles of the sections are hidden :/

HTML IDs are in the wrong elements. they should be in the title of each section. @ArunTeltia, you have to adjust the IDs so that the browser scrolls to the correct element, i.e. title of each section.

**Comment by ArunTeltia** [comment]
Having a look at it @abdus

**Comment by abdus** [comment]
any updates, Arun?

**Comment by ArunTeltia** [comment]
Please have a look now @abdus and sorry for the delay

**Comment by abdus** [comment]
forgot to add `#impact`? clicking on `What We Do?` does not work because there is no element with id `impact`. this, in turn, makes the page unresponsive (and later crashes) as the `while` loop for finding element becomes infinite. 
just to be safe in the future, add a time limit in that `while` loop.

**Comment by ArunTeltia** [comment]
Fixing these issues bhaiya will remember these in future thank you 😀

**Comment by Manvityagi** [comment]
> Fixing these issues bhaiya will remember these in future thank you 😀

Have you done this @ArunTetlia?

**Comment by ArunTeltia** [comment]
done @abdus @Manvityagi

**Comment by Manvityagi** [comment]
[](https://gifyu.com/image/1fil)

@ArunTeltia See the difference, this what I meant in https://github.com/Girl-Code-It/Girl-Code-It-Website-Frontend/pull/187#issuecomment-855414153 

See if this can be fixed, otherwise, I will merge your PR for now as it is.

**Comment by ArunTeltia** [comment]
Mostly this is hiding behind the navbar, okay having a look at this

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
