### PR TITLE
New python tech members. Task 2

### LINKED ISSUE #158: New python members
Am working on this @Manvityagi

### PR DESCRIPTION
**Pull request by akshay1027**
# Description

 New python tech members. Task 2
@Manvityagi 

Fixed #158 

screenshots:  

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have squashed my commits
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by Manvityagi — CHANGES_REQUESTED** [review]
On some view ports, the singular cards are not in center
[](https://gifyu.com/image/5L3Y)

**Comment by Manvityagi** [comment]
> On some view ports, the singular cards are not in center
> [](https://gifyu.com/image/5L3Y)

@akshay1027

**Comment by akshay1027** [comment]
Ohh, I will try to fix this!

**Comment by akshay1027** [comment]
responsiveness:

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
