### PR TITLE
Feature/Navbar Component

### PR DESCRIPTION
**Pull request by divanshurox**
# Description

Fixed Issue #12.

Added NavBar component.

Added Dependencies: 
"react-bootstrap": "^1.0.1"

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I have squashed my commits
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by SinghVikram97** [comment]
Please fix the position of nav drawer icon at screen size <350px . Everything else is good

**Comment by Manvityagi** [comment]
@divanshurox Please do the changes as requested by @SinghVikram97  and also squash your commits before making the PR.
One PR should have only 1 commit. 
Also please change the name of your branch from temp to "feature/navbar" and commit message shall also be something like "feature/navbar - Added navbar component. 

And lastly, please drop an email to girlcodeit@gmail.com to be added to the communication channel with all other contributors.

**Comment by divanshurox** [comment]
Done that, Thanks!

**Comment by Manvityagi** [comment]
@SinghVikram97 Please do the final review, Will merge the PR if its final

**Comment by SinghVikram97** [comment]
Yes it looks good now. @Manvityagi

**Comment by Manvityagi** [comment]
Ok, Merging!

**Pull request merged**
