### PR TITLE
"Meettheteam" card UI

### LINKED ISSUE #152: Add Hover Effects on cards in "/meettheteam" page
Adding Hover Effects on cards in "/meettheteam" page!

### PR DESCRIPTION
**Pull request by akshay1027**
# Description
 Added hover effects, margin, box-shadow effects and scale effects to the cards

Fixed #152 

Screenshots:

Image when hovered on a particular card!

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by akshay1027** [comment]
please review this @Manvityagi, I have spent some time on this, let me know if you need any changes! Thank you!

**Review by Manvityagi — APPROVED** [review]
Looks great @akshay1027

**Comment by akshay1027** [comment]
Thank you! Can you please add labels @Manvityagi

**Comment by Manvityagi** [comment]
What labels are you expecting? Are you a GSSOC participant?

**Comment by akshay1027** [comment]
Yes! Am a gssoc participate, sorry I didn't mention it

**Comment by Manvityagi** [comment]
> Yes! Am a gssoc participate, sorry I didn't mention it

This project is not a part of GSSOC, 

The following projects are a part of GSSOC. 
https://github.com/Girl-Code-It/Opportunity-Calendar-Backend
https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend

**Comment by akshay1027** [comment]
Ohh, no worries, happy to contribute 😌🙌🏻

**Pull request merged**
