### PR TITLE
feature/Impact

### LINKED ISSUE #17: Make ImpactCard and Impact component

### PR DESCRIPTION
**Pull request by Meghag5**
# Description

Changed ImpactList to ImpactCard and ImpactCard and Impact are updated. Added Impact.module.css and added two images image1.svg and image2.svg.

Fixed #17 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Manvityagi** [comment]
@Meghag5 Why have you not updated the Pull request details. Please see scenario 1 from the video I shared.

**Comment by Meghag5** [comment]
impact component is created

**Comment by Manvityagi** [comment]
Mention the issue number @Meghag5, 
Like fixed #(issue number), eg. Fixed #17 

See the issue number for this component from issues

**Comment by Meghag5** [comment]
> Mention the issue number @Meghag5,
> Like fixed #(issue number), eg. Fixed #17
> 
> See the issue number for this component from issues

done

**Pull request closed without merging**
